name = "modern-stack-api"
compatibility_date = "2024-11-01"

# 这里的 main 指向入口文件，虽然我们在命令里指定了，但配置文件里写上也更规范
main = "src/index.ts"

[observability]
enabled = true

[[kv_namespaces]]
binding = "USER_CACHE"
id = "175dfa6ee4034733a14b918e213bb8fb"
preview_id = "daa59cba4e504a2d818ee0c658b3498a"